services:
  frontend:
    build: ./frontend
    container_name: frontend
  backend:
    build: ./backend
    container_name: backend
    networks:
      - new_net
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - new_net
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
      - adminer
    networks:
      - new_net

networks:
  new_net:
    driver: bridge
    name: new_net